PARAMETERS = {
    "Emotions": {
        "postive-mood-low-energy": "Postive mood, low energy",
        "postive-mood-high-energy": "Postive mood, high energy",
        "negative-mood-low-energy": "Negative mood, low energy",
        "negative-mood-high-energy": "Negative mood, high energy",
    },
    "Size-y, structure-y words": {
        "big-and-free": "Big and free",
        "big-and-structured": "Big and structured",
        "small-and-structured": "Small and structured",
        "small-and-free": "Small and free",
    },
    "Rendering": {
        "4k": "4K ",
        "realistic": "Realistic",
        "octane": "Octane",
        "shot-on-imax-70mm": "Shot on IMAX 70mm",
        "surreal-photorealistic": "[surreal + photorealistic]",
        "hyperdetailed-insane-details-intricate": "[hyperdetailed + insane details + intricate] ",
        "ornate-elegant-luxury-realist": "[ornate + elegant + luxury + realist]",
        "volummetric-lighting": "volummetric lighting",
        "redshift": "redshift",
        "lumion": "lumion",
        "nixie-tube-inspiration": "nixie tube inspiration",
        "ultradetailed": "ultradetailed",
    },
    "Vibes": {
        "vaporwave-neon-pink-blue": "Vaporwave: neon, pink, blue",
        "post-apocalyptic": "Post-apocalyptic",
        "gothic-fantasy": "Gothic, fantasy",
        "cybernetic-sci-fi": "Cybernetic, sci-fi",
        "steampunk": "Steampunk",
        "memphis": "Memphis",
        "dieselpunk": "Dieselpunk",
        "afrofuturism": "Afrofuturism",
        "cyberpunk": "Cyberpunk",
        "biopunk-organic": "Biopunk, organic",
    },
    "Analog Illustrations": {
        "stencil-street-art-banksy": "Stencil, street art, Banksy",
        "ballpoint-pen-art": "Ballpoint pen art",
        "pencil-sketch": "Pencil sketch",
        "pencil-drawing": "Pencil drawing",
        "political-cartoon-from-us-newspaper": "Political cartoon from U.S. newspaper",
        "charcoal-sketch": "Charcoal sketch",
        "woodcut": "Woodcut",
        "field-journal-line-art": "Field journal line art",
        "colouring-in-sheet": "Colouring-in sheet",
        "etching": "Etching",
    },
    "Ancient artsy": {
        "cave-paintings": "Cave paintings",
        "ancient-egyptian-mural": "Ancient Egyptian mural",
        "ancient-egypt-papyrus": "Ancient Egypt papyrus",
        "fayum-portrait": "Fayum portrait",
        "decorative-minoan-mural": "Decorative Minoan mural",
        "roman-mosaic": "Roman mosaic",
        "ancient-roman-painting": "Ancient Roman painting",
        "nuremberg-chronicle": "Nuremberg Chronicle",
        "byzantine-icon": "Byzantine icon",
        "giilded-codex": "Giilded codex",
    },
    "Digital artsy": {
        "alegria-corporate-memphis": "Alegria, 'corporate memphis'",
        "collage-photocollage-magazine-collage": "Collage, photocollage, magazine collage",
        "vector-art": "Vector art",
        "watercolor-pen": "Watercolor & pen",
        "screen-printing": "Screen printing",
        "low-poly": "Low poly",
        "layered-paper": "Layered paper",
        "sticker-illustration": "Sticker illustration",
        "storybook": "Storybook",
        "digital-painting": "Digital painting",
    },
    "Camera XYZ": {
        "extreme-close-up": "Extreme close-up",
        "close-up": "Close-up",
        "medium-shot": "Medium shot",
        "long-shot": "Long shot",
        "extreme-long-shot": "Extreme long shot",
    },
    "Photo Documentation": {
        "surrounded-by-foliage-dreamy-autochrome-pinhole-photography": "surrounded by foliage, dreamy autochrome pinhole photography",
        "studio-photography-dark-grey-background-softly-backlit-gentle-smoke-effect": "studio photography, dark grey background, softly backlit, gentle smoke effect",
        "dramatic-low-key-neon-lighting-light-painting-editorial-photo-from-magazine": "dramatic low-key neon lighting, light painting, editorial photo from magazine",
    },
    "Camera position": {
        "overhead-view": "Overhead view",
        "low-angle": "Low angle",
        "aerial-view": "Aerial view",
        "tilted-frame": "Tilted frame",
        "over-the-shoulder-shot": "Over-the-shoulder shot",
    },
    "Aesthetics": {
        "abstract-tech": "Abstract Tech",
        "acid-pixie": "Acid Pixie",
        "acidwave": "Acidwave",
        "adventure-pulp": "Adventure Pulp",
        "adventurecore": "Adventurecore",
        "aetherpunk": "Aetherpunk",
        "afrofuturism": "Afrofuturism",
        "afro-victorian": "Afro-Victorian",
        "after-hours": "After Hours",
        "agropeople": "Agropeople",
        "alien": "Alien",
        "alternative": "Alternative",
        "americana": "Americana",
        "analog-horror": "Analog Horror",
        "american-pioneers": "American Pioneers",
        "american-revolution": "American Revolution",
        "american-tourist-traps": "American Tourist Traps",
        "ancient-egypt": "Ancient Egypt",
        "androgynous": "Androgynous",
        "anemoiacore": "Anemoiacore",
        "angelcore": "Angelcore",
        "anglocore": "Anglocore",
        "anglo-gothic": "Anglo Gothic",
        "angura-kei": "Angura Kei",
        "animecore": "Animecore",
        "antique-grunge": "Antique Grunge",
        "anti-fashion": "Anti-Fashion",
        "art-academia": "Art Academia",
        "arts-and-crafts-movement": "Arts and Crafts Movement",
        "art-deco": "Art Deco",
        "art-hoe": "Art Hoe",
        "art-nouveau": "Art Nouveau",
        "asian-baby-girl": "Asian Baby Girl",
        "athlete": "Athlete",
        "atompunk": "Atompunk",
        "auroracore": "Auroracore",
        "autumn": "Autumn",
        "avant-apocalypse": "Avant Apocalypse",
        "avant-garde": "Avant-garde",
        "babycore": "Babycore",
        "babygirl": "Babygirl",
        "baddie": "Baddie",
        "ballet-academia": "Ballet Academia",
        "baltic-violence-tumblr": "Baltic Violence Tumblr",
        "barbiecore": "Barbiecore",
        "bardcore": "Bardcore",
        "baroque": "Baroque",
        "bastardcore": "Bastardcore",
        "bdsm": "BDSM",
        "beach-bunny": "Beach Bunny",
        "beach-day": "Beach Day",
        "beatnik": "Beatnik",
        "biker": "Biker",
        "bimbocore": "Bimbocore",
        "biohazard": "Biohazard",
        "biopunk": "Biopunk",
        "bizarro-fiction": "Bizarro Fiction",
        "black-holed-meme": "Black-Holed Meme",
        "bloomcore": "Bloomcore",
        "bodikon": "Bodikon",
        "bohemian": "Bohemian",
        "bombacore": "Bombacore",
        "bookstore-girl": "Bookstore Girl",
        "bosozoku": "Bosozoku",
        "boujee": "Boujee",
        "brazilcore": "Brazilcore",
        "breakcore": "Breakcore",
        "britpop": "Britpop",
        "brocore": "Brocore",
        "bronzepunk": "Bronzepunk",
        "bunni-frog": "Bunni Frog",
        "bubble-bujo": "Bubble Bujo",
        "bubble-goth": "Bubble Goth",
        "bubblegum-bitch": "Bubblegum Bitch",
        "bubblegum-witch": "Bubblegum Witch",
        "cabincore": "Cabincore",
        "cagole": "Cagole",
        "camp": "Camp",
        "campcore": "Campcore",
        "candycore": "Candycore",
        "cargopunk": "Cargopunk",
        "carnivalcore": "Carnivalcore",
        "cartelcore": "Cartelcore",
        "cartooncore": "Cartooncore",
        "casino": "Casino",
        "cassette-futurism": "Cassette Futurism",
        "celtic": "Celtic",
        "changelingcore": "Changelingcore",
        "chaotic-academia": "Chaotic Academia",
        "chav": "Chav",
        "cheiron-crush": "Cheiron Crush",
        "cherry-emoji-twitter": "Cherry Emoji Twitter",
        "chic-modernist": "Chic Modernist",
        "cholo": "Cholo",
        "christcore": "Christcore",
        "christian-girl-autumn": "Christian Girl Autumn",
        "christmas": "Christmas",
        "city-pop": "City Pop",
        "classic-academia": "Classic Academia",
        "classic-lolita": "Classic Lolita",
        "classicism": "Classicism",
        "cleancore": "Cleancore",
        "clockpunk": "Clockpunk",
        "cloudcore": "Cloudcore",
        "clowncore": "Clowncore",
        "club": "Club",
        "club-kids": "Club Kids",
        "coastal-grandmother": "Coastal Grandmother",
        "cutecore": "Cutecore",
        "coffee-housecafe": "Coffee House/Cafe",
        "coffinwood": "Coffinwood",
        "colourful-black": "Colourful Black",
        "comfycozy": "Comfy/Cozy",
        "common-white-girl": "Common White Girl",
        "concore": "Concore",
        "constructivism": "Constructivism",
        "corporate": "Corporate",
        "corporate-memphis": "Corporate Memphis",
        "corporate-punk": "Corporate Punk",
        "cottagecore": "Cottagecore",
        "cottagegore": "Cottagegore",
        "coquette": "Coquette",
        "country": "Country",
        "c-pop": "C-Pop",
        "crackhead": "Crackhead",
        "craftcore": "Craftcore",
        "cripplepunk": "Cripplepunk",
        "crowcore": "Crowcore",
        "crustpunk": "Crustpunk",
        "cryptid-academia": "Cryptid Academia",
        "cryptidcore": "Cryptidcore",
        "cubism": "Cubism",
        "cuddle-party": "Cuddle Party",
        "cultcore": "Cultcore",
        "cult-party-kei": "Cult Party Kei",
        "cyber-minimalism": "Cyber Minimalism",
        "cyberdelic": "Cyberdelic",
        "cyber-fairy-grunge": "Cyber Fairy Grunge",
        "cyberghetto": "Cyberghetto",
        "cybergoth": "Cybergoth",
        "cybergrunge": "Cybergrunge",
        "cyberneticpunk": "CyberneticPunk",
        "cyberparadism": "Cyberparadism",
        "cyberpop": "Cyberpop",
        "cyberprep": "Cyberprep",
        "cyberpunk": "Cyberpunk",
        "danish-pastel": "Danish Pastel",
        "darkerrorcore": "DarkErrorcore",
        "dark-academia": "Dark Academia",
        "dark-fantasy": "Dark Fantasy",
        "dark-naturalism": "Dark Naturalism",
        "dark-nautical": "Dark Nautical",
        "dark-nymphet": "Dark Nymphet",
        "dark-paradise": "Dark Paradise",
        "darkcore": "Darkcore",
        "darkest-academia": "Darkest Academia",
        "daydreampunk": "Daydreampunk",
        "dazecore": "Dazecore",
        "de-stijl": "De Stijl",
        "deathcore": "Deathcore",
        "deathrock": "Deathrock",
        "decopunk": "Decopunk",
        "decora": "Decora",
        "delicate-sweet": "Delicate Sweet",
        "desertwave": "Desertwave",
        "desi-romantic-academia": "Desi Romantic Academia",
        "dethereal": "Dethereal",
        "devilcore": "Devilcore",
        "dieselpunk": "Dieselpunk",
        "diner": "Diner",
        "dionysism": "Dionysism",
        "dolly-kei": "Dolly Kei",
        "downtown-girl": "Downtown Girl",
        "dracopunk": "Dracopunk",
        "dragoncore": "Dragoncore",
        "drainer": "Drainer",
        "dreamcore": "Dreamcore",
        "dreamy": "Dreamy",
        "drugcore": "Drugcore",
        "dual-kawaii": "Dual Kawaii",
        "duckcore": "Duckcore",
        "dullcore": "Dullcore",
        "dungeon-synth": "Dungeon Synth",
        "fairy-academia": "Fairy Academia",
        "fairy-grunge": "Fairy Grunge",
        "fairy-kei": "Fairy Kei",
        "fairy-tale": "Fairy Tale",
        "fairycore": "Fairycore",
        "fanfare": "Fanfare",
        "fantasy": "Fantasy",
        "fantasy-astronomy": "Fantasy Astronomy",
        "fashwave": "Fashwave",
        "fauvism": "Fauvism",
        "fawncore": "Fawncore",
        "femboy": "Femboy",
        "femcel-weeaboo": "Femcel Weeaboo",
        "femme-fatale": "Femme Fatale",
        "feralcore": "Feralcore",
        "film-noir": "Film Noir",
        "flapper": "Flapper",
        "fluowave": "Fluowave",
        "folk-punk": "Folk Punk",
        "foodie": "Foodie",
        "forestpunk": "Forestpunk",
        "french-girl": "French Girl",
        "french-girly": "French Girly",
        "frogcore": "Frogcore",
        "frutiger-aero": "Frutiger Aero",
        "funky-seasons": "Funky Seasons",
        "furry": "Furry",
        "futago": "Futago",
        "futurism": "Futurism",
        "gadgetpunk": "Gadgetpunk",
        "game-night": "Game Night",
        "gamercore": "Gamercore",
        "gamine": "Gamine",
        "geek": "Geek",
        "gen-x-soft-club": "Gen X Soft Club",
        "ghostcore": "Ghostcore",
        "girl-next-door": "Girl-Next-Door",
        "glam-girl": "Glam Girl",
        "glam-rock": "Glam Rock",
        "glitchcore": "Glitchcore",
        "gloomcore": "Gloomcore",
        "glowwave": "Glowwave",
        "goblin-academia": "Goblin Academia",
        "goblincore": "Goblincore",
        "golden-age-of-detective-fiction": "Golden Age of Detective Fiction",
        "golden-hour": "Golden Hour",
        "gopnik": "Gopnik",
        "gorecore": "Gorecore",
        "gorpcore": "Gorpcore",
        "goth": "Goth",
        "gothcore": "Gothcore",
        "gothic": "Gothic",
        "gothic-lolita": "Gothic Lolita",
        "grandmillenial": "Grandmillenial",
        "grandparentcore": "Grandparentcore",
        "greaser": "Greaser",
        "green-academia": "Green Academia",
        "grifes": "Grifes",
        "grindhouse": "Grindhouse",
        "groundcore": "Groundcore",
        "grunge": "Grunge",
        "gull-girl": "Gull Girl",
        "gurokawa": "Gurokawa",
        "gyaru": "Gyaru",
        "hackercore": "Hackercore",
        "halloween": "Halloween",
        "hallyu": "Hallyu",
        "happycore": "Happycore",
        "hatecore": "Hatecore",
        "hauntology": "Hauntology",
        "haussmann-paris": "Haussmann Paris",
        "health-goth": "Health Goth",
        "heatwave": "Heatwave",
        "heistcore": "Heistcore",
        "hellenic": "Hellenic",
        "hermaphroditus": "Hermaphroditus",
        "hermitpunk": "Hermitpunk",
        "hexatron": "Hexatron",
        "hi-nrg": "Hi-NRG",
        "high-school-dream": "High School Dream",
        "hikecore": "Hikecore",
        "hime-lolita": "Hime Lolita",
        "hip-hop": "Hip-Hop",
        "hippie": "Hippie",
        "hipster": "Hipster",
        "hispanicore": "Hispanicore",
        "historical-americana": "Historical Americana",
        "holosexual": "Holosexual",
        "honeycore": "Honeycore",
        "horror": "Horror",
        "horror-academia": "Horror Academia",
        "hot-topic": "Hot Topic",
        "hustlewave": "Hustlewave",
        "hydrogen": "Hydrogen",
        "hyperpop": "Hyperpop",
        "la-sape": "La Sape",
        "labcore": "Labcore",
        "laborwave": "Laborwave",
        "lagenlook": "Lagenlook",
        "larme-kei": "Larme Kei",
        "libertywave": "Libertywave",
        "light-academia": "Light Academia",
        "lightcore": "Lightcore",
        "lightningwave": "Lightningwave",
        "lil-girl": "Lil Girl",
        "liminal-space": "Liminal Space",
        "lit-kid": "Lit Kid",
        "lo-fi": "Lo-Fi",
        "lobotomy-chic": "Lobotomy-Chic",
        "lolita": "Lolita",
        "long-island": "Long Island",
        "lounge": "Lounge",
        "lovecore": "Lovecore",
        "lunarpunk": "Lunarpunk",
        "macaute": "Macaute",
        "mad-scientist": "Mad Scientist",
        "magewave": "Magewave",
        "magical-girls": "Magical Girls",
        "maidcore": "Maidcore",
        "mallgoth": "Mallgoth",
        "mall-pop": "Mall Pop",
        "mall-ninja": "Mall Ninja",
        "maximalism": "Maximalism",
        "mcbling": "McBling",
        "meatcore": "Meatcore",
        "medicalcore": "Medicalcore",
        "medieval": "Medieval",
        "mtv-green-sky": "MTV Green Sky",
        "memphis": "Memphis",
        "mermaid": "Mermaid",
        "metal": "Metal",
        "metalcore": "Metalcore",
        "metalheart": "Metalheart",
        "metrosexual": "Metrosexual",
        "miami-metro": "Miami Metro",
        "midwest-emo": "Midwest Emo",
        "midwest-gothic": "Midwest Gothic",
        "military": "Military",
        "milk": "Milk",
        "miniaturecore": "Miniaturecore",
        "minimalism": "Minimalism",
        "miscellaneous-academia": "Miscellaneous Academia",
        "mizuiro-kaiwai": "Mizuiro Kaiwai",
        "mod": "Mod",
        "modernism": "Modernism",
        "mori-kei": "Mori Kei",
        "morute": "Morute",
        "mote-kei": "Mote Kei",
        "mulchcore": "Mulchcore",
        "mushroomcore": "Mushroomcore",
        "mosscore": "Mosscore",
        "ms-paint": "Ms Paint",
        "musical-academia": "Musical Academia",
        "mythpunk": "Mythpunk",
        "nanopunk": "Nanopunk",
        "naturecore": "Naturecore",
        "nautical": "Nautical",
        "nazi-chic": "Nazi Chic",
        "neko": "Neko",
        "neo-romanism": "Neo-Romanism",
        "neo-tokyo": "Neo-Tokyo",
        "nerd": "Nerd",
        "nerdcore": "Nerdcore",
        "new-england-gothic": "New England Gothic",
        "new-age": "New Age",
        "new-money": "New Money",
        "new-romantic": "New Romantic",
        "new-wave": "New Wave",
        "nihilcore": "Nihilcore",
        "nintencore": "Nintencore",
        "normcore": "Normcore",
        "northerness": "Northerness",
        "nostalgiacore": "Nostalgiacore",
        "nuclear": "Nuclear",
        "nu-goth": "Nu-Goth",
        "nymphet": "Nymphet",
        "pachuco": "Pachuco",
        "pale-grunge": "Pale Grunge",
        "paleocore": "Paleocore",
        "palewave": "Palewave",
        "paramilitary": "Paramilitary",
        "party-animal": "Party Animal",
        "party-kei": "Party Kei",
        "pastel": "Pastel",
        "pastel-academia": "Pastel Academia",
        "pastel-goth": "Pastel Goth",
        "pastel-punk": "Pastel Punk",
        "pc-music": "PC Music",
        "peach": "Peach",
        "pearly": "Pearly",
        "peoplehood": "Peoplehood",
        "photorealism": "Photorealism",
        "pink-parisian": "Pink Parisian",
        "pink-princess": "Pink Princess",
        "pin-up": "Pin-up",
        "pinterest-coquette": "Pinterest Coquette",
        "pirate": "Pirate",
        "pixel-cutie": "Pixel Cutie",
        "pixiecore": "Pixiecore",
        "plaguecore": "Plaguecore",
        "plant-mom": "Plant Mom",
        "playboy": "Playboy",
        "pop": "Pop",
        "pop-art": "Pop Art",
        "pop-kei": "Pop Kei",
        "post-apocalyptic": "Post-Apocalyptic",
        "post-impressionism": "Post-Impressionism",
        "post-punk": "Post-Punk",
        "post-rock": "Post-rock",
        "powwow-step": "Powwow Step",
        "prairiecore": "Prairiecore",
        "pre-raphaelite": "Pre-Raphaelite",
        "prehistoricore": "Prehistoricore",
        "preppy": "Preppy",
        "rb": "R&B",
        "racaille": "Racaille",
        "ragecore": "Ragecore",
        "rainbowcore": "Rainbowcore",
        "rainy-day": "Rainy Day",
        "randumb": "Randumb",
        "rangercore": "Rangercore",
        "ratcore": "Ratcore",
        "ravencore": "Ravencore",
        "raver": "Raver",
        "real-life-super-hero": "Real Life Super Hero",
        "realism": "Realism",
        "reefwave": "Reefwave",
        "regency": "Regency",
        "regional-gothic": "Regional Gothic",
        "retro-futurism": "Retro-Futurism",
        "rivethead": "Rivethead",
        "roaring-20s": "Roaring 20s",
        "robotics-kid": "Robotics Kid",
        "rock": "Rock",
        "rockabilly": "Rockabilly",
        "rococo": "Rococo",
        "roguecore": "Roguecore",
        "rollerwave": "Rollerwave",
        "roma": "Roma",
        "romantic-academia": "Romantic Academia",
        "romantic-goth": "Romantic Goth",
        "romantic-italian": "Romantic Italian",
        "romanticism": "Romanticism",
        "rotcore": "Rotcore",
        "royalcore": "Royalcore",
        "rusticcore": "Rusticcore",
        "sad-people": "Sad people",
        "salon-kei": "Salon Kei",
        "salvagepunk": "Salvagepunk",
        "sandalpunk": "Sandalpunk",
        "sanriocore": "Sanriocore",
        "scene": "Scene",
        "schizowave": "Schizowave",
        "schoolgirl-lifestyle": "Schoolgirl Lifestyle",
        "science-academia": "Science Academia",
        "scoutcore": "Scoutcore",
        "scrapbook": "Scrapbook",
        "scrapper": "Scrapper",
        "seapunk": "Seapunk",
        "selkiecore": "Selkiecore",
        "shabby-chic": "Shabby Chic",
        "shanzhai": "Shanzhai",
        "sh\u0101-m\u01ce-t\u00e8": "Sh\u0101 m\u01ce t\u00e8",
        "sharpies": "Sharpies",
        "shibuya-punk": "Shibuya Punk",
        "shironuri": "Shironuri",
        "shoegaze": "Shoegaze",
        "sizz": "Sizz",
        "skater": "Skater",
        "skinheads": "Skinheads",
        "sleepycore": "Sleepycore",
        "slimepunk": "Slimepunk",
        "sloanies": "Sloanies",
        "slutcore": "Slutcore",
        "snowdrop": "Snowdrop",
        "snow-bunny": "Snow Bunny",
        "soft-apocalypse": "Soft Apocalypse",
        "soft-grunge": "Soft Grunge",
        "soft-indie": "Soft indie",
        "soft-macabre": "Soft Macabre",
        "softie": "Softie",
        "soggy": "Soggy",
        "solarpunk": "Solarpunk",
        "southern-belle": "Southern Belle",
        "southern-gothic": "Southern Gothic",
        "sovietwave": "Sovietwave",
        "spacecore": "Spacecore",
        "space-cowboy": "Space Cowboy",
        "sparklecore": "Sparklecore",
        "spiritcore": "Spiritcore",
        "spring": "Spring",
        "spy-fiction": "Spy fiction",
        "starrflesh": "Starrflesh",
        "steampunk": "Steampunk",
        "steelpunk": "Steelpunk",
        "stilyagi": "Stilyagi",
        "stimwave": "Stimwave",
        "stonepunk": "Stonepunk",
        "stoner": "Stoner",
        "stripcore": "Stripcore",
        "studyblr": "Studyblr",
        "studyplace": "Studyplace",
        "suburban-gothic": "Suburban Gothic",
        "sukeban": "Sukeban",
        "summer": "Summer",
        "superflat-pop": "Superflat Pop",
        "suprematism": "Suprematism",
        "surf-crush": "Surf Crush",
        "surrealism": "Surrealism",
        "surreal-memer": "Surreal Memer",
        "swenkas": "Swenkas",
        "swordpunk": "Swordpunk",
        "synthwave": "Synthwave",
        "tacticool": "Tacticool",
        "takenokozoku": "Takenokozoku",
        "tanbi-kei": "Tanbi Kei",
        "technical-scene": "Technical Scene",
        "technocore": "Technocore",
        "technozen": "Technozen",
        "techwear": "Techwear",
        "teddies": "Teddies",
        "teenqueen": "Teenqueen",
        "teethcore": "Teethcore",
        "tenwave": "Tenwave",
        "terrorwave": "Terrorwave",
        "teslapunk": "Teslapunk",
        "that-girl": "That Girl",
        "theatre-academia": "Theatre Academia",
        "theatre-kids": "Theatre Kids",
        "thrasher": "Thrasher",
        "thriftcore": "Thriftcore",
        "tiki": "Tiki",
        "tinkercore": "Tinkercore",
        "tinycore": "Tinycore",
        "tomboy": "Tomboy",
        "trad-goth": "Trad Goth",
        "traditional-korean": "Traditional Korean",
        "trailer-park-princess": "Trailer Park Princess",
        "trashcore": "Trashcore",
        "traumacore": "Traumacore",
        "trenchcore": "Trenchcore",
        "trendercore": "Trendercore",
        "trillwave": "Trillwave",
        "tropical": "Tropical",
        "tumblewave": "Tumblewave",
        "tupinipunk": "Tupinipunk",
        "tweencore": "Tweencore",
        "twee": "Twee",
        "variousxyz": "VARIOUSXYZ",
        "vacation-dadcore": "Vacation Dadcore",
        "vampire": "Vampire",
        "vaporwave": "Vaporwave",
        "vectorheart": "Vectorheart",
        "vibrant-academia": "Vibrant Academia",
        "victorian": "Victorian",
        "victorian-goth": "Victorian Goth",
        "viking": "Viking",
        "villagecore": "Villagecore",
        "villaincore": "Villaincore",
        "vintage-british-sportsman": "Vintage British Sportsman",
        "vintage-parisian": "Vintage Parisian",
        "virgos-tears": "Virgo's Tears",
        "visual-kei": "Visual Kei",
        "vsco": "VSCO",
        "vsco-preppy": "VSCO Preppy",
        "voidcore": "Voidcore",
        "voidpunk": "Voidpunk",
        "vorticism": "Vorticism",
        "vulture-culture": "Vulture Culture",
        "wabi-sabi": "Wabi-Sabi",
        "waif": "Waif",
        "waldorf": "Waldorf",
        "wanderlust": "Wanderlust",
        "warmcore": "Warmcore",
        "weathercore": "Weathercore",
        "web-creep": "Web Creep",
        "weeaboo": "Weeaboo",
        "weirdcore": "Weirdcore",
        "werewolf": "Werewolf",
        "western": "Western",
        "wetcore": "Wetcore",
        "wild-child": "Wild Child",
        "winter": "Winter",
        "winter-fairy-coquette": "Winter Fairy Coquette",
        "witchy-academia": "Witchy Academia",
        "witch-house": "Witch House",
        "witchcore": "Witchcore",
        "wizardcore": "Wizardcore",
        "wonderland": "Wonderland",
        "woodland-goth": "Woodland Goth",
        "wormcore": "Wormcore",
        "writer-academia": "Writer Academia",
        "wuxia": "Wuxia",
    },
}
