PARAMETERS = {
    "Emotions": {
        "postive-mood-low-energy": "Postive mood, low energy",
        "postive-mood-high-energy": "Postive mood, high energy",
        "negative-mood-low-energy": "Negative mood, low energy",
        "negative-mood-high-energy": "Negative mood, high energy",
    },
    "Size-y, structure-y words": {
        "big-and-free": "Big and free",
        "big-and-structured": "Big and structured",
        "small-and-structured": "Small and structured",
        "small-and-free": "Small and free",
    },
    "Rendering": {
        "4k": "4K ",
        "realistic": "Realistic",
        "octane": "Octane",
        "shot-on-imax-70mm": "Shot on IMAX 70mm",
        "surreal-photorealistic": "surreal, photorealistic",
        "hyperdetailed-insane-details-intricate": "hyperdetailed, insane details, intricate",
        "ornate-elegant-luxury-realist": "ornate, elegant, luxury, realist",
        "volummetric-lighting": "volummetric lighting",
        "redshift": "redshift",
        "lumion": "lumion",
        "nixie-tube-inspiration": "nixie tube inspiration",
        "ultradetailed": "ultradetailed",
    },
    "Vibes": {
        "vaporwave-neon-pink-blue": "Vaporwave: neon, pink, blue",
        "post-apocalyptic": "Post-apocalyptic",
        "gothic-fantasy": "Gothic, fantasy",
        "cybernetic-sci-fi": "Cybernetic, sci-fi",
        "steampunk": "Steampunk",
        "memphis": "Memphis",
        "dieselpunk": "Dieselpunk",
        "afrofuturism": "Afrofuturism",
        "cyberpunk": "Cyberpunk",
        "biopunk-organic": "Biopunk, organic",
    },
    "Analog Illustrations": {
        "stencil-street-art-banksy": "Stencil, street art, Banksy",
        "ballpoint-pen-art": "Ballpoint pen art",
        "pencil-sketch": "Pencil sketch",
        "pencil-drawing": "Pencil drawing",
        "political-cartoon-from-us-newspaper": "Political cartoon from U.S. newspaper",
        "charcoal-sketch": "Charcoal sketch",
        "woodcut": "Woodcut",
        "field-journal-line-art": "Field journal line art",
        "colouring-in-sheet": "Colouring-in sheet",
        "etching": "Etching",
    },
    "Ancient artsy": {
        "cave-paintings": "Cave paintings",
        "ancient-egyptian-mural": "Ancient Egyptian mural",
        "ancient-egypt-papyrus": "Ancient Egypt papyrus",
        "fayum-portrait": "Fayum portrait",
        "decorative-minoan-mural": "Decorative Minoan mural",
        "roman-mosaic": "Roman mosaic",
        "ancient-roman-painting": "Ancient Roman painting",
        "nuremberg-chronicle": "Nuremberg Chronicle",
        "byzantine-icon": "Byzantine icon",
        "giilded-codex": "Giilded codex",
    },
    "Digital artsy": {
        "alegria-corporate-memphis": "Alegria, corporate memphis",
        "collage-photocollage-magazine-collage": "Collage, photocollage, magazine collage",
        "vector-art": "Vector art",
        "watercolor-pen": "Watercolor & pen",
        "screen-printing": "Screen printing",
        "low-poly": "Low poly",
        "layered-paper": "Layered paper",
        "sticker-illustration": "Sticker illustration",
        "storybook": "Storybook",
        "digital-painting": "Digital painting",
    },
    "Camera XYZ": {
        "extreme-close-up": "Extreme close-up",
        "close-up": "Close-up",
        "medium-shot": "Medium shot",
        "long-shot": "Long shot",
        "extreme-long-shot": "Extreme long shot",
    },
    "Photo Documentation": {
        "surrounded-by-foliage-dreamy-autochrome-pinhole-photography": "surrounded by foliage, dreamy autochrome pinhole photography",
        "studio-photography-dark-grey-background-softly-backlit-gentle-smoke-effect-photo-courtesy-museum-of-art": "studio photography, dark grey background, softly backlit, gentle smoke effect, photo courtesy Museum of Art",
        "dramatic-low-key-neon-lighting-light-painting-editorial-photo-from-magazine": "dramatic low-key neon lighting, light painting, editorial photo from magazine",
    },
    "Camera position": {
        "overhead-view": "Overhead view",
        "low-angle": "Low angle",
        "aerial-view": "Aerial view",
        "tilted-frame": "Tilted frame",
        "over-the-shoulder-shot": "Over-the-shoulder shot",
    },
    "Aesthetics": {
        "abstract-tech": "Abstract Tech",
        "acid-pixie": "Acid Pixie",
        "acidwave": "Acidwave",
        "adventure-pulp": "Adventure Pulp",
        "adventurecore": "Adventurecore",
        "aetherpunk": "Aetherpunk",
        "afrofuturism": "Afrofuturism",
        "afro-victorian": "Afro-Victorian",
        "after-hours": "After Hours",
        "agropeople": "Agropeople",
        "alien": "Alien",
        "alternative": "Alternative",
        "americana": "Americana",
        "analog-horror": "Analog Horror",
        "american-pioneers": "American Pioneers",
        "american-revolution": "American Revolution",
        "american-tourist-traps": "American Tourist Traps",
        "ancient-egypt": "Ancient Egypt",
        "androgynous": "Androgynous",
        "anemoiacore": "Anemoiacore",
        "angelcore": "Angelcore",
        "anglocore": "Anglocore",
        "anglo-gothic": "Anglo Gothic",
        "angura-kei": "Angura Kei",
        "animecore": "Animecore",
        "antique-grunge": "Antique Grunge",
        "anti-fashion": "Anti-Fashion",
        "art-academia": "Art Academia",
        "arts-and-crafts-movement": "Arts and Crafts Movement",
        "art-deco": "Art Deco",
        "art-hoe": "Art Hoe",
        "art-nouveau": "Art Nouveau",
        "asian-baby-girl": "Asian Baby Girl",
        "athlete": "Athlete",
        "atompunk": "Atompunk",
        "auroracore": "Auroracore",
        "autumn": "Autumn",
        "avant-apocalypse": "Avant Apocalypse",
        "avant-garde": "Avant-garde",
        "babycore": "Babycore",
        "babygirl": "Babygirl",
        "baddie": "Baddie",
        "ballet-academia": "Ballet Academia",
        "baltic-violence-tumblr": "Baltic Violence Tumblr",
        "barbiecore": "Barbiecore",
        "bardcore": "Bardcore",
        "baroque": "Baroque",
        "bastardcore": "Bastardcore",
        "bdsm": "BDSM",
        "beach-bunny": "Beach Bunny",
        "beach-day": "Beach Day",
        "beatnik": "Beatnik",
        "biker": "Biker",
        "bimbocore": "Bimbocore",
        "biohazard": "Biohazard",
        "biopunk": "Biopunk",
        "bizarro-fiction": "Bizarro Fiction",
        "black-holed-meme": "Black-Holed Meme",
        "bloomcore": "Bloomcore",
        "bodikon": "Bodikon",
        "bohemian": "Bohemian",
        "bombacore": "Bombacore",
        "bookstore-girl": "Bookstore Girl",
        "bosozoku": "Bosozoku",
        "boujee": "Boujee",
        "brazilcore": "Brazilcore",
        "breakcore": "Breakcore",
        "britpop": "Britpop",
        "brocore": "Brocore",
        "bronzepunk": "Bronzepunk",
        "bunni-frog": "Bunni Frog",
        "bubble-bujo": "Bubble Bujo",
        "bubble-goth": "Bubble Goth",
        "bubblegum-bitch": "Bubblegum Bitch",
        "bubblegum-witch": "Bubblegum Witch",
        "cabincore": "Cabincore",
        "cagole": "Cagole",
        "camp": "Camp",
        "campcore": "Campcore",
        "candycore": "Candycore",
        "cargopunk": "Cargopunk",
        "carnivalcore": "Carnivalcore",
        "cartelcore": "Cartelcore",
        "cartooncore": "Cartooncore",
        "casino": "Casino",
        "cassette-futurism": "Cassette Futurism",
        "celtic": "Celtic",
        "changelingcore": "Changelingcore",
        "chaotic-academia": "Chaotic Academia",
        "chav": "Chav",
        "cheiron-crush": "Cheiron Crush",
        "cherry-emoji-twitter": "Cherry Emoji Twitter",
        "chic-modernist": "Chic Modernist",
        "cholo": "Cholo",
        "christcore": "Christcore",
        "christian-girl-autumn": "Christian Girl Autumn",
        "christmas": "Christmas",
        "city-pop": "City Pop",
        "classic-academia": "Classic Academia",
        "classic-lolita": "Classic Lolita",
        "classicism": "Classicism",
        "cleancore": "Cleancore",
        "clockpunk": "Clockpunk",
        "cloudcore": "Cloudcore",
        "clowncore": "Clowncore",
        "club": "Club",
        "club-kids": "Club Kids",
        "coastal-grandmother": "Coastal Grandmother",
        "cutecore": "Cutecore",
        "coffee-house-cafe": "Coffee House, Cafe",
        "coffinwood": "Coffinwood",
        "colourful-black": "Colourful Black",
        "comfy-cozy": "Comfy, Cozy",
        "common-white-girl": "Common White Girl",
        "concore": "Concore",
        "constructivism": "Constructivism",
        "corporate": "Corporate",
        "corporate-memphis": "Corporate Memphis",
        "corporate-punk": "Corporate Punk",
        "cottagecore": "Cottagecore",
        "cottagegore": "Cottagegore",
        "coquette": "Coquette",
        "country": "Country",
        "c-pop": "C-Pop",
        "crackhead": "Crackhead",
        "craftcore": "Craftcore",
        "cripplepunk": "Cripplepunk",
        "crowcore": "Crowcore",
        "crustpunk": "Crustpunk",
        "cryptid-academia": "Cryptid Academia",
        "cryptidcore": "Cryptidcore",
        "cubism": "Cubism",
        "cuddle-party": "Cuddle Party",
        "cultcore": "Cultcore",
        "cult-party-kei": "Cult Party Kei",
        "cyber-minimalism": "Cyber Minimalism",
        "cyberdelic": "Cyberdelic",
        "cyber-fairy-grunge": "Cyber Fairy Grunge",
        "cyberghetto": "Cyberghetto",
        "cybergoth": "Cybergoth",
        "cybergrunge": "Cybergrunge",
        "cyberneticpunk": "CyberneticPunk",
        "cyberparadism": "Cyberparadism",
        "cyberpop": "Cyberpop",
        "cyberprep": "Cyberprep",
        "cyberpunk": "Cyberpunk",
        "danish-pastel": "Danish Pastel",
        "darkerrorcore": "DarkErrorcore",
        "dark-academia": "Dark Academia",
        "dark-fantasy": "Dark Fantasy",
        "dark-naturalism": "Dark Naturalism",
        "dark-nautical": "Dark Nautical",
        "dark-nymphet": "Dark Nymphet",
        "dark-paradise": "Dark Paradise",
        "darkcore": "Darkcore",
        "darkest-academia": "Darkest Academia",
        "daydreampunk": "Daydreampunk",
        "dazecore": "Dazecore",
        "de-stijl": "De Stijl",
        "deathcore": "Deathcore",
        "deathrock": "Deathrock",
        "decopunk": "Decopunk",
        "decora": "Decora",
        "delicate-sweet": "Delicate Sweet",
        "desertwave": "Desertwave",
        "desi-romantic-academia": "Desi Romantic Academia",
        "dethereal": "Dethereal",
        "devilcore": "Devilcore",
        "dieselpunk": "Dieselpunk",
        "diner": "Diner",
        "dionysism": "Dionysism",
        "dolly-kei": "Dolly Kei",
        "downtown-girl": "Downtown Girl",
        "dracopunk": "Dracopunk",
        "dragoncore": "Dragoncore",
        "drainer": "Drainer",
        "dreamcore": "Dreamcore",
        "dreamy": "Dreamy",
        "drugcore": "Drugcore",
        "dual-kawaii": "Dual Kawaii",
        "duckcore": "Duckcore",
        "dullcore": "Dullcore",
        "dungeon-synth": "Dungeon Synth",
        "fairy-academia": "Fairy Academia",
        "fairy-grunge": "Fairy Grunge",
        "fairy-kei": "Fairy Kei",
        "fairy-tale": "Fairy Tale",
        "fairycore": "Fairycore",
        "fanfare": "Fanfare",
        "fantasy": "Fantasy",
        "fantasy-astronomy": "Fantasy Astronomy",
        "fashwave": "Fashwave",
        "fauvism": "Fauvism",
        "fawncore": "Fawncore",
        "femboy": "Femboy",
        "femcel-weeaboo": "Femcel Weeaboo",
        "femme-fatale": "Femme Fatale",
        "feralcore": "Feralcore",
        "film-noir": "Film Noir",
        "flapper": "Flapper",
        "fluowave": "Fluowave",
        "folk-punk": "Folk Punk",
        "foodie": "Foodie",
        "forestpunk": "Forestpunk",
        "french-girl": "French Girl",
        "french-girly": "French Girly",
        "frogcore": "Frogcore",
        "frutiger-aero": "Frutiger Aero",
        "funky-seasons": "Funky Seasons",
        "furry": "Furry",
        "futago": "Futago",
        "futurism": "Futurism",
        "gadgetpunk": "Gadgetpunk",
        "game-night": "Game Night",
        "gamercore": "Gamercore",
        "gamine": "Gamine",
        "geek": "Geek",
        "gen-x-soft-club": "Gen X Soft Club",
        "ghostcore": "Ghostcore",
        "girl-next-door": "Girl-Next-Door",
        "glam-girl": "Glam Girl",
        "glam-rock": "Glam Rock",
        "glitchcore": "Glitchcore",
        "gloomcore": "Gloomcore",
        "glowwave": "Glowwave",
        "goblin-academia": "Goblin Academia",
        "goblincore": "Goblincore",
        "golden-age-of-detective-fiction": "Golden Age of Detective Fiction",
        "golden-hour": "Golden Hour",
        "gopnik": "Gopnik",
        "gorecore": "Gorecore",
        "gorpcore": "Gorpcore",
        "goth": "Goth",
        "gothcore": "Gothcore",
        "gothic": "Gothic",
        "gothic-lolita": "Gothic Lolita",
        "grandmillenial": "Grandmillenial",
        "grandparentcore": "Grandparentcore",
        "greaser": "Greaser",
        "green-academia": "Green Academia",
        "grifes": "Grifes",
        "grindhouse": "Grindhouse",
        "groundcore": "Groundcore",
        "grunge": "Grunge",
        "gull-girl": "Gull Girl",
        "gurokawa": "Gurokawa",
        "gyaru": "Gyaru",
        "hackercore": "Hackercore",
        "halloween": "Halloween",
        "hallyu": "Hallyu",
        "happycore": "Happycore",
        "hatecore": "Hatecore",
        "hauntology": "Hauntology",
        "haussmann-paris": "Haussmann Paris",
        "health-goth": "Health Goth",
        "heatwave": "Heatwave",
        "heistcore": "Heistcore",
        "hellenic": "Hellenic",
        "hermaphroditus": "Hermaphroditus",
        "hermitpunk": "Hermitpunk",
        "hexatron": "Hexatron",
        "hi-nrg": "Hi-NRG",
        "high-school-dream": "High School Dream",
        "hikecore": "Hikecore",
        "hime-lolita": "Hime Lolita",
        "hip-hop": "Hip-Hop",
        "hippie": "Hippie",
        "hipster": "Hipster",
        "hispanicore": "Hispanicore",
        "historical-americana": "Historical Americana",
        "holosexual": "Holosexual",
        "honeycore": "Honeycore",
        "horror": "Horror",
        "horror-academia": "Horror Academia",
        "hot-topic": "Hot Topic",
        "hustlewave": "Hustlewave",
        "hydrogen": "Hydrogen",
        "hyperpop": "Hyperpop",
        "la-sape": "La Sape",
        "labcore": "Labcore",
        "laborwave": "Laborwave",
        "lagenlook": "Lagenlook",
        "larme-kei": "Larme Kei",
        "libertywave": "Libertywave",
        "light-academia": "Light Academia",
        "lightcore": "Lightcore",
        "lightningwave": "Lightningwave",
        "lil-girl": "Lil Girl",
        "liminal-space": "Liminal Space",
        "lit-kid": "Lit Kid",
        "lo-fi": "Lo-Fi",
        "lobotomy-chic": "Lobotomy-Chic",
        "lolita": "Lolita",
        "long-island": "Long Island",
        "lounge": "Lounge",
        "lovecore": "Lovecore",
        "lunarpunk": "Lunarpunk",
        "macaute": "Macaute",
        "mad-scientist": "Mad Scientist",
        "magewave": "Magewave",
        "magical-girls": "Magical Girls",
        "maidcore": "Maidcore",
        "mallgoth": "Mallgoth",
        "mall-pop": "Mall Pop",
        "mall-ninja": "Mall Ninja",
        "maximalism": "Maximalism",
        "mcbling": "McBling",
        "meatcore": "Meatcore",
        "medicalcore": "Medicalcore",
        "medieval": "Medieval",
        "mtv-green-sky": "MTV Green Sky",
        "memphis": "Memphis",
        "mermaid": "Mermaid",
        "metal": "Metal",
        "metalcore": "Metalcore",
        "metalheart": "Metalheart",
        "metrosexual": "Metrosexual",
        "miami-metro": "Miami Metro",
        "midwest-emo": "Midwest Emo",
        "midwest-gothic": "Midwest Gothic",
        "military": "Military",
        "milk": "Milk",
        "miniaturecore": "Miniaturecore",
        "minimalism": "Minimalism",
        "miscellaneous-academia": "Miscellaneous Academia",
        "mizuiro-kaiwai": "Mizuiro Kaiwai",
        "mod": "Mod",
        "modernism": "Modernism",
        "mori-kei": "Mori Kei",
        "morute": "Morute",
        "mote-kei": "Mote Kei",
        "mulchcore": "Mulchcore",
        "mushroomcore": "Mushroomcore",
        "mosscore": "Mosscore",
        "ms-paint": "Ms Paint",
        "musical-academia": "Musical Academia",
        "mythpunk": "Mythpunk",
        "nanopunk": "Nanopunk",
        "naturecore": "Naturecore",
        "nautical": "Nautical",
        "nazi-chic": "Nazi Chic",
        "neko": "Neko",
        "neo-romanism": "Neo-Romanism",
        "neo-tokyo": "Neo-Tokyo",
        "nerd": "Nerd",
        "nerdcore": "Nerdcore",
        "new-england-gothic": "New England Gothic",
        "new-age": "New Age",
        "new-money": "New Money",
        "new-romantic": "New Romantic",
        "new-wave": "New Wave",
        "nihilcore": "Nihilcore",
        "nintencore": "Nintencore",
        "normcore": "Normcore",
        "northerness": "Northerness",
        "nostalgiacore": "Nostalgiacore",
        "nuclear": "Nuclear",
        "nu-goth": "Nu-Goth",
        "nymphet": "Nymphet",
        "pachuco": "Pachuco",
        "pale-grunge": "Pale Grunge",
        "paleocore": "Paleocore",
        "palewave": "Palewave",
        "paramilitary": "Paramilitary",
        "party-animal": "Party Animal",
        "party-kei": "Party Kei",
        "pastel": "Pastel",
        "pastel-academia": "Pastel Academia",
        "pastel-goth": "Pastel Goth",
        "pastel-punk": "Pastel Punk",
        "pc-music": "PC Music",
        "peach": "Peach",
        "pearly": "Pearly",
        "peoplehood": "Peoplehood",
        "photorealism": "Photorealism",
        "pink-parisian": "Pink Parisian",
        "pink-princess": "Pink Princess",
        "pin-up": "Pin-up",
        "pinterest-coquette": "Pinterest Coquette",
        "pirate": "Pirate",
        "pixel-cutie": "Pixel Cutie",
        "pixiecore": "Pixiecore",
        "plaguecore": "Plaguecore",
        "plant-mom": "Plant Mom",
        "playboy": "Playboy",
        "pop": "Pop",
        "pop-art": "Pop Art",
        "pop-kei": "Pop Kei",
        "post-apocalyptic": "Post-Apocalyptic",
        "post-impressionism": "Post-Impressionism",
        "post-punk": "Post-Punk",
        "post-rock": "Post-rock",
        "powwow-step": "Powwow Step",
        "prairiecore": "Prairiecore",
        "pre-raphaelite": "Pre-Raphaelite",
        "prehistoricore": "Prehistoricore",
        "preppy": "Preppy",
        "rb": "R&B",
        "racaille": "Racaille",
        "ragecore": "Ragecore",
        "rainbowcore": "Rainbowcore",
        "rainy-day": "Rainy Day",
        "randumb": "Randumb",
        "rangercore": "Rangercore",
        "ratcore": "Ratcore",
        "ravencore": "Ravencore",
        "raver": "Raver",
        "real-life-super-hero": "Real Life Super Hero",
        "realism": "Realism",
        "reefwave": "Reefwave",
        "regency": "Regency",
        "regional-gothic": "Regional Gothic",
        "retro-futurism": "Retro-Futurism",
        "rivethead": "Rivethead",
        "roaring-20s": "Roaring 20s",
        "robotics-kid": "Robotics Kid",
        "rock": "Rock",
        "rockabilly": "Rockabilly",
        "rococo": "Rococo",
        "roguecore": "Roguecore",
        "rollerwave": "Rollerwave",
        "roma": "Roma",
        "romantic-academia": "Romantic Academia",
        "romantic-goth": "Romantic Goth",
        "romantic-italian": "Romantic Italian",
        "romanticism": "Romanticism",
        "rotcore": "Rotcore",
        "royalcore": "Royalcore",
        "rusticcore": "Rusticcore",
        "sad-people": "Sad people",
        "salon-kei": "Salon Kei",
        "salvagepunk": "Salvagepunk",
        "sandalpunk": "Sandalpunk",
        "sanriocore": "Sanriocore",
        "scene": "Scene",
        "schizowave": "Schizowave",
        "schoolgirl-lifestyle": "Schoolgirl Lifestyle",
        "science-academia": "Science Academia",
        "scoutcore": "Scoutcore",
        "scrapbook": "Scrapbook",
        "scrapper": "Scrapper",
        "seapunk": "Seapunk",
        "selkiecore": "Selkiecore",
        "shabby-chic": "Shabby Chic",
        "shanzhai": "Shanzhai",
        "sh\u0101-m\u01ce-t\u00e8": "Sh\u0101 m\u01ce t\u00e8",
        "sharpies": "Sharpies",
        "shibuya-punk": "Shibuya Punk",
        "shironuri": "Shironuri",
        "shoegaze": "Shoegaze",
        "sizz": "Sizz",
        "skater": "Skater",
        "skinheads": "Skinheads",
        "sleepycore": "Sleepycore",
        "slimepunk": "Slimepunk",
        "sloanies": "Sloanies",
        "slutcore": "Slutcore",
        "snowdrop": "Snowdrop",
        "snow-bunny": "Snow Bunny",
        "soft-apocalypse": "Soft Apocalypse",
        "soft-grunge": "Soft Grunge",
        "soft-indie": "Soft indie",
        "soft-macabre": "Soft Macabre",
        "softie": "Softie",
        "soggy": "Soggy",
        "solarpunk": "Solarpunk",
        "southern-belle": "Southern Belle",
        "southern-gothic": "Southern Gothic",
        "sovietwave": "Sovietwave",
        "spacecore": "Spacecore",
        "space-cowboy": "Space Cowboy",
        "sparklecore": "Sparklecore",
        "spiritcore": "Spiritcore",
        "spring": "Spring",
        "spy-fiction": "Spy fiction",
        "starrflesh": "Starrflesh",
        "steampunk": "Steampunk",
        "steelpunk": "Steelpunk",
        "stilyagi": "Stilyagi",
        "stimwave": "Stimwave",
        "stonepunk": "Stonepunk",
        "stoner": "Stoner",
        "stripcore": "Stripcore",
        "studyblr": "Studyblr",
        "studyplace": "Studyplace",
        "suburban-gothic": "Suburban Gothic",
        "sukeban": "Sukeban",
        "summer": "Summer",
        "superflat-pop": "Superflat Pop",
        "suprematism": "Suprematism",
        "surf-crush": "Surf Crush",
        "surrealism": "Surrealism",
        "surreal-memer": "Surreal Memer",
        "swenkas": "Swenkas",
        "swordpunk": "Swordpunk",
        "synthwave": "Synthwave",
        "tacticool": "Tacticool",
        "takenokozoku": "Takenokozoku",
        "tanbi-kei": "Tanbi Kei",
        "technical-scene": "Technical Scene",
        "technocore": "Technocore",
        "technozen": "Technozen",
        "techwear": "Techwear",
        "teddies": "Teddies",
        "teenqueen": "Teenqueen",
        "teethcore": "Teethcore",
        "tenwave": "Tenwave",
        "terrorwave": "Terrorwave",
        "teslapunk": "Teslapunk",
        "that-girl": "That Girl",
        "theatre-academia": "Theatre Academia",
        "theatre-kids": "Theatre Kids",
        "thrasher": "Thrasher",
        "thriftcore": "Thriftcore",
        "tiki": "Tiki",
        "tinkercore": "Tinkercore",
        "tinycore": "Tinycore",
        "tomboy": "Tomboy",
        "trad-goth": "Trad Goth",
        "traditional-korean": "Traditional Korean",
        "trailer-park-princess": "Trailer Park Princess",
        "trashcore": "Trashcore",
        "traumacore": "Traumacore",
        "trenchcore": "Trenchcore",
        "trendercore": "Trendercore",
        "trillwave": "Trillwave",
        "tropical": "Tropical",
        "tumblewave": "Tumblewave",
        "tupinipunk": "Tupinipunk",
        "tweencore": "Tweencore",
        "twee": "Twee",
        "variousxyz": "VARIOUSXYZ",
        "vacation-dadcore": "Vacation Dadcore",
        "vampire": "Vampire",
        "vaporwave": "Vaporwave",
        "vectorheart": "Vectorheart",
        "vibrant-academia": "Vibrant Academia",
        "victorian": "Victorian",
        "victorian-goth": "Victorian Goth",
        "viking": "Viking",
        "villagecore": "Villagecore",
        "villaincore": "Villaincore",
        "vintage-british-sportsman": "Vintage British Sportsman",
        "vintage-parisian": "Vintage Parisian",
        "virgos-tears": "Virgo's Tears",
        "visual-kei": "Visual Kei",
        "vsco": "VSCO",
        "vsco-preppy": "VSCO Preppy",
        "voidcore": "Voidcore",
        "voidpunk": "Voidpunk",
        "vorticism": "Vorticism",
        "vulture-culture": "Vulture Culture",
        "wabi-sabi": "Wabi-Sabi",
        "waif": "Waif",
        "waldorf": "Waldorf",
        "wanderlust": "Wanderlust",
        "warmcore": "Warmcore",
        "weathercore": "Weathercore",
        "web-creep": "Web Creep",
        "weeaboo": "Weeaboo",
        "weirdcore": "Weirdcore",
        "werewolf": "Werewolf",
        "western": "Western",
        "wetcore": "Wetcore",
        "wild-child": "Wild Child",
        "winter": "Winter",
        "winter-fairy-coquette": "Winter Fairy Coquette",
        "witchy-academia": "Witchy Academia",
        "witch-house": "Witch House",
        "witchcore": "Witchcore",
        "wizardcore": "Wizardcore",
        "wonderland": "Wonderland",
        "woodland-goth": "Woodland Goth",
        "wormcore": "Wormcore",
        "writer-academia": "Writer Academia",
        "wuxia": "Wuxia",
    },
    "Lighting prompts": {
        "golden-hour": "Golden hour",
        "blue-hour": "Blue hour",
        "midday": "Midday",
        "overcast": "Overcast",
        "shadow-silhouette": "shadow & silhouette",
    },
    "Mood Lighting": {
        "warm-lighting": "Warm lighting",
        "cold": "Cold",
        "flash-photography": "Flash photography",
        "colourful-lighting-defined-colours": "Colourful lighting, defined colours",
        "defined-real-light-source": "Defined real light source",
        "high-key-lighting": "High-key lighting",
        "low-key-lighting": "Low-key lighting",
        "backlighting-backlit": "Backlighting, backlit",
        "studio-lighting": "Studio lighting",
        "defined-direction": "Defined direction",
    },
    "Creative film types": {
        "kodachrome": "Kodachrome",
        "autochrome": "Autochrome",
        "lomography": "Lomography",
        "polaroid-instax": "Polaroid, Instax",
        "cameraphone": "Cameraphone",
        "cctv": "CCTV",
        "disposable-camera": "Disposable camera",
        "daguerrotype": "Daguerrotype",
        "camera-obscura": "Camera obscura",
        "double-exposure": "Double exposure",
    },
    "Creative film types II": {
        "cyanotype": "Cyanotype",
        "black-and-white-tri-x-400tx": "Black and white, Tri-X 400TX",
        "redscale-photography": "Redscale photography",
        "infrared-photography": "Infrared photography",
        "bleach-bypass": "Bleach bypass",
        "instagram-hipstamatic-2015": "Instagram, Hipstamatic, 2015",
        "contact-sheet": "Contact sheet",
        "colour-splash": "Colour splash",
        "solarised": "Solarised",
        "anaglyph": "Anaglyph",
    },
    "Film TV prompts": {
        "tv-show-friends-season-3-1997": "TV show Friends, Season 3 (1997)",
        "the-grand-budapest-hotel-2014": "The Grand Budapest Hotel (2014)",
        "tv-series-frasier-1994": "TV series Frasier (1994)",
        "netflix-show-stranger-things-2016": "Netflix show, Stranger Things (2016)",
        "jaws-1975": "Jaws (1975)",
        "tv-show-starsky-hutch-1975": "TV show Starsky & Hutch (1975)",
        "blade-runner-2049-2017": "Blade Runner 2049 (2017)",
        "breaking-bad-season-4-2011": "Breaking Bad, Season 4 (2011)",
        "citizen-kane-1941": "Citizen Kane (1941)",
        "amelie-2001": "Amelie (2001)",
    },
    "Photo genre": {
        "action-sports-photography-fast-shutter-speed-from-espn": "action sports photography, fast shutter speed from ESPN",
        "editorial-fashion-photography-from-vogue-magazine": "editorial fashion photography, from Vogue magazine",
        "candid-street-portrait-photojournalism-from-the-new-york-times": "candid street portrait, photojournalism from The New York Times",
        "professional-corporate-portrait-from-investor-prospectus": "professional corporate portrait, from investor prospectus",
        "flash-photography-event-photography-film-premier-photograph-from-celebrity-news-website": "flash photography, event photography, film premier photograph from celebrity news website",
    },
    "Portrait photographer prompts": {
        "george-hurrell": "George Hurrell",
        "martin-schoeller": "Martin Schoeller",
        "dorothea-lange": "Dorothea Lange",
        "lee-jeffries": "Lee Jeffries",
        "terry-richardson": "Terry Richardson",
    },
    "Camera lens": {
        "fast-shutter-speed": "Fast shutter speed",
        "slow-shutter-speed": "Slow shutter speed",
        "bokeh": "Bokeh",
        "tilt-shift-photography": "Tilt shift photography",
        "motion-blur": "Motion blur",
        "telephoto-lens": "Telephoto lens",
        "macro-lens-macro-photo": "Macro lens, macro photo",
        "wide-angle-lens-15mm": "Wide angle lens, 15mm",
        "fish-eye-lens": "Fish-eye lens",
        "deep-depth-of-field": "Deep depth of field",
    },
    "Illustration styles, instructional": {
        "blueprint": "Blueprint",
        "patent-drawing": "Patent drawing",
        "cutaway": "Cutaway",
        "ikea-manual": "IKEA manual",
        "instruction-manual": "Instruction manual",
        "botanical-illustration": "Botanical illustration",
        "mythological-map": "Mythological map",
        "voynich-manuscript": "Voynich manuscript",
        "scientific-diagram": "Scientific diagram",
        "voroni-diagram": "Voroni diagram",
    },
    "Illustrations, 3D, textured": {
        "isometric-3d": "Isometric 3D",
        "3d-render-houdini-3d-octane-3d": "3D render, houdini 3D, octane 3D",
        "claymation-aardman-animation": "Claymation, Aardman Animation",
        "felt-pieces": "Felt pieces",
        "fabric-pattern": "Fabric pattern",
        "black-velvet-edgar-leeteg": "Black velvet, Edgar Leeteg",
        "scratch-art-foil-art-gold-on-black": "Scratch art, foil art, gold on black",
        "perler-beads": "Perler beads",
        "screenshot-of-x-from-game": "Screenshot of X from game",
        "tattoo": "Tattoo",
    },
    "Illustration styles, character, cartoon": {
        "character-reference-sheet": "Character reference sheet",
        "comic-book-art": "Comic book art",
        "anime": "Anime",
        "pixar": "Pixar",
        "studio-ghibli": "Studio Ghibli",
        "vintage-disney": "Vintage Disney",
        "pixel-art": "Pixel Art",
        "1990s-disney-cel-shading": "1990s Disney, cel shading",
        "1970s-grainy-vintage-illustration": "1970s grainy vintage illustration",
        "hanna-barbera-1960s-scooby-doo-flintstones-jetsons-etc": "Hanna Barbera, 1960s, Scooby Doo, Flintstones, Jetsons, etc",
    },
    "in the style of\u2026 (animated TV shows + films)": {
        "south-park": "South Park",
        "the-simpsons": "The Simpsons",
        "spirited-away": "Spirited Away",
        "family-guy": "Family Guy",
        "bojack-horseman": "Bojack Horseman",
        "adventure-time": "Adventure Time",
        "powerpuff-girls": "Powerpuff Girls",
        "vintage-looney-tunes-1961": "vintage Looney Tunes (1961)",
        "pixars-up": "Pixar's 'Up'",
        "the-far-side-print-comic": "The Far Side (print comic)",
    },
    "in the style of\u2026 (particular illustrators)": {
        "beatrix-potter-peter-rabbit-etc": "Beatrix Potter (Peter Rabbit etc)",
        "quentin-blake-from-roald-dahl-books-etc": "Quentin Blake (from Roald Dahl books, etc)",
        "hayao-miyazaki-studio-ghibli": "Hayao Miyazaki (Studio Ghibli)",
        "bill-watterson-calvin-hobbes": "Bill Watterson (Calvin & Hobbes)",
        "maurice-sendak-where-the-wild-things-are": "Maurice Sendak (Where the Wild Things Are)",
        "ralph-steadman": "Ralph Steadman",
        "norman-rockwell": "Norman Rockwell",
        "dr-seuss": "Dr. Seuss",
        "tove-jansson-the-moomins": "Tove Jansson (The Moomins)",
        "wanda-g\u00e1g": "Wanda G\u00e1g",
    },
    "Illustration styles, analog media, colour": {
        "crayon": "Crayon",
        "childs-drawing-children-drawing": "Child's drawing, children drawing",
        "acrylic-on-canvas": "Acrylic on canvas",
        "watercolor": "Watercolor",
        "coloured-pencil-detailed": "Coloured pencil, detailed",
        "oil-painting": "Oil painting",
        "ukiyo-e": "Ukiyo-e",
        "chinese-watercolor": "Chinese watercolor",
        "pastels": "Pastels",
        "airbrush": "Airbrush",
    },
    "Renaissance - modern art movements": {
        "renaissance-painting-1400-1600": "Renaissance painting (1400-1600)",
        "mannerism": "Mannerism",
        "baroque": "Baroque",
        "rococo": "Rococo",
        "neoclassicism": "Neoclassicism",
        "realism": "Realism",
        "art-nouveau": "Art Nouveau",
        "impressionism": "Impressionism",
        "post-impressionism": "Post-impressionism",
        "symbolist-painting": "Symbolist painting",
    },
    "Modern art movements": {
        "art-deco": "Art deco",
        "abstract-expressionism": "Abstract expressionism",
        "bauhaus": "Bauhaus",
        "colour-field-painting": "Colour field painting",
        "cubism": "Cubism",
        "constructivist": "Constructivist",
        "dada": "Dada",
        "de-stijl": "De Stijl",
        "expressionism-expressionist": "Expressionism, expressionist",
        "fauvism": "Fauvism",
    },
    "Modern art movements II": {
        "futurism": "Futurism",
        "metaphysical-painting-de-chirico-italian-carlo-carr\u00e0": "Metaphysical painting, de Chirico, Italian, Carlo Carr\u00e0",
        "surrealism-surrealist-magritte-dali-andre-breton-max-ernst": "Surrealism, surrealist, Magritte, Dali, Andre Breton, Max Ernst",
        "pop-art-warhol-1960s": "Pop Art, Warhol, 1960s",
        "street-art-graffiti-urban-public-art-independent": "Street art, graffiti, urban public art, independent",
        "suprematism-abstract-geometric-kazimir-malevich-1913": "Suprematism, abstract, geometric, Kazimir Malevich , 1913",
        "mexican-muralism-diego-rivera-jos\u00e9-clemente-orozco-david-alfaro-siqueiros": "Mexican muralism, Diego Rivera, Jos\u00e9 Clemente Orozco, David Alfaro Siqueiros",
        "neo-expressionism-1980s": "Neo-Expressionism, 1980s",
        "orphism-orphist-franti\u0161ek-kupka-robert-delaunay-sonia-delaunay": "Orphism, Orphist,  Franti\u0161ek Kupka, Robert Delaunay, Sonia Delaunay",
        "street-photography-urban-candid-flaneur-unposed": "Street photography, urban, candid, flaneur, unposed",
    },
    "Assorted artist tests": {
        "edward-hopper-1942": "Edward Hopper, 1942",
        "keith-haring": "Keith Haring",
        "salvador-dali": "Salvador Dali ",
        "georges-surat": "Georges Surat",
        "vincent-van-gogh": "Vincent van Gogh",
    },
    "More distinctive artist styles": {
        "thomas-kinkade": "Thomas Kinkade",
        "lisa-frank": "Lisa Frank",
        "basquiat": "Basquiat",
        "simon-st\u00e5lenhag": "Simon St\u00e5lenhag",
        "zdzis\u0142aw-beksi\u0144ski": "Zdzis\u0142aw Beksi\u0144ski",
        "hr-giger": "HR Giger",
        "robert-crumb": "Robert Crumb",
        "hieronymus-bosch": "Hieronymus Bosch",
        "gustav-kilmt": "Gustav Kilmt",
        "roy-lichenstein": "Roy Lichenstein",
    },
    "Things for human bodies": {
        "clothes-shoes-and-individual-clothing-items": "Clothes, shoes, and individual clothing items",
        "costumes-outfits-costumery-theatrical-halloween-cosplay": "Costumes, outfits, costumery, theatrical, Halloween, cosplay",
        "hairstyles-haircuts": "Hairstyles, haircuts",
        "nail-art": "Nail art",
        "tattoos-and-body-art": "Tattoos and body art",
        "fashion-fashion-photography": "Fashion, fashion photography",
        "historic-futuristic-attire-armor-technology-alternate-history-imaginary-culture-fantasy": "Historic, futuristic attire, armor, technology, alternate history, imaginary culture, fantasy",
        "jewellery-necklace-rings-etc": "Jewellery, necklace, rings, etc",
        "accessories-bags": "Accessories, bags ",
        "makeup-cosmetics-face-paint": "Makeup, cosmetics, face paint ",
    },
    "Places and spaces": {
        "architecture-buildings-wings": "Architecture, buildings, wings",
        "stage-sets-theatrical-sets-tv-sets": "Stage sets, theatrical sets, TV sets",
        "domestic-interiors-home-design": "Domestic interiors, home design",
        "commercial-interiors-hospitality-public-buildings-workplaces": "Commercial interiors, hospitality, public buildings, workplaces",
        "public-realm": "Public realm",
        "gardens-landscaping-natural-outdoor-spaces": "Gardens, landscaping, natural, outdoor spaces",
        "inflatables-parade-floats-hot-air-balloons": "Inflatables, parade floats, hot air balloons",
        "attractions": "Attractions",
        "furniture-furnishings-rugs-sofas-beds-curtains-etcetera": "Furniture, furnishings, rugs, sofas, beds, curtains, etcetera",
        "events-festivals-event-design-event-planning-event-decoration": "Events, festivals, event design, event planning, event decoration",
    },
    "Crafty arts, paper & textiles": {
        "papercraft-origami": "Papercraft, origami",
        "diorama-dolls-house": "Diorama, dolls house",
        "pop-up-book": "Pop-up book",
        "paper-embossing": "Paper embossing",
        "papier-mache": "Papier mache",
        "needle-felting": "Needle felting",
        "appliqu\u00e9-needlework": "Appliqu\u00e9 needlework",
        "embroidery": "Embroidery",
        "knitting-patterns": "Knitting patterns",
        "amigurumi": "Amigurumi",
    },
    "Crafty arts, ceramics & glass": {
        "ceramic-bust-kintsugi": "Ceramic, bust, Kintsugi",
        "clay-pottery-sculpture": "Clay, pottery, sculpture",
        "porcelain": "Porcelain",
        "azulejo-portuguese-blue-and-white-painted-tile-art": "Azulejo, Portuguese blue-and-white painted tile art",
        "stained-glass": "Stained glass",
        "glass-paperweight": "Glass paperweight",
        "snowglobe": "Snowglobe",
        "bubblegram": "Bubblegram",
        "crystal-figure": "Crystal figure",
        "tile-art-mosaic": "Tile art, mosaic",
    },
    "Sculpture & statue material examples": {
        "bronze-statue": "Bronze statue",
        "marble-statue": "Marble statue",
        "terracotta-warriors": "Terracotta warriors",
        "jade-sculpture": "Jade sculpture",
        "gold-silver-etc": "Gold, silver, etc",
        "butter-sculpture": "Butter sculpture",
        "sand-sculpture": "Sand sculpture",
        "topiary-plant-sculpture": "Topiary, plant sculpture",
        "ice-carving": "Ice carving",
        "plastic-fiberglass": "Plastic, fiberglass",
    },
    "Alien": {
        "octane-render": "Octane render",
        "dan-seagrave": "Dan seagrave",
        "artstation": "Artstation",
        "space": "Space",
        "alien-dragon-flying": "Alien dragon flying",
        "outer-space": "Outer space",
        "alien": "Alien",
        "highly-detailed": "Highly detailed",
        "8k": "8k",
        "intricate": "Intricate",
        "epic": "Epic",
        "depth": "Depth",
        "epic-nebula": "Epic nebula",
        "hr-giger": "Hr giger",
        "alien-rabbit": "Alien rabbit",
        "ambient-light": "Ambient light",
        "aliens": "Aliens",
        "concept-art": "Concept art",
        "vivid-sky": "Vivid sky",
        "alien-landscape": "Alien landscape",
        "matte-painting": "Matte painting",
        "desolate-landscape": "Desolate landscape",
        "distance": "Distance",
        "cosmic": "Cosmic",
        "interstellar": "Interstellar",
        "mysterious": "Mysterious",
        "hyper-realistic": "Hyper realistic",
        "noah-bradley": "Noah bradley",
        "greg-rutkowski": "Greg rutkowski",
        "earth": "Earth",
    },
    "Futuristic": {
        "highly-detailed": "Highly detailed",
        "octane-render": "Octane render",
        "artstation": "Artstation",
        "futuristic": "Futuristic",
        "4k": "4k",
        "unreal-engine": "Unreal engine",
        "intricate": "Intricate",
        "digital-art": "Digital art",
        "dystopian-art": "Dystopian art",
        "cry-engine": "Cry engine",
        "futuristic-city": "Futuristic city",
        "8k": "8k",
        "trending": "Trending",
        "epic": "Epic",
        "depth": "Depth",
        "art-nouveau": "Art nouveau",
        "vray": "Vray",
        "airbrush": "Airbrush",
        "starry-sky": "Starry sky",
        "fantasy": "Fantasy",
        "hyperrealism": "Hyperrealism",
        "photorealistic-concept-art": "Photorealistic concept art",
        "birds-eye": "Birds eye",
        "vista-view": "Vista view",
        "clear": "Clear",
        "looming": "Looming",
        "super-wide-angle": "Super wide angle",
        "peter-mohrbacher": "Peter mohrbacher",
        "cinematic": "Cinematic",
        "futuristic-cyberpunk-skyscrapers": "Futuristic cyberpunk skyscrapers",
        "huge-futuristic-temple-city": "Huge futuristic temple city",
        "magical-sparkling-lake": "Magical sparkling lake",
        "blender": "Blender",
        "wearing": "Wearing",
        "hyperrealistic": "Hyperrealistic",
        "fortress-gateway": "Fortress gateway",
        "matte-painting": "Matte painting",
        "concept-art": "Concept art",
        "high-detail": "High detail",
        "vladimir-kush": "Vladimir kush",
        "michael-whelan": "Michael whelan",
        "bill-stoneham": "Bill stoneham",
        "tsutomu-nihei": "Tsutomu nihei",
        "jane-graverol": "Jane graverol",
        "kay-sage": "Kay sage",
        "gothic-building": "Gothic building",
        "cyberpunk-neon-city": "Cyberpunk neon city",
        "purple-energy-sabers": "Purple energy sabers",
        "glass": "Glass",
        "crisp-detailed-photo": "Crisp detailed photo",
        "tall-glass": "Tall glass",
        "grape-soda": "Grape soda",
        "dripping-condensation": "Dripping condensation",
        "dynamic-lighting": "Dynamic lighting",
        "dramatic-lighting": "Dramatic lighting",
        "year-2134": "Year 2134",
        "majestic": "Majestic",
        "liminal": "Liminal",
        "halo-ark": "Halo ark",
    },
    "Photography": {
        "portrait": "Portrait",
        "character-photography": "Character photography",
        "photography": "Photography",
        "hyper-realistic": "Hyper realistic",
        "35-mm-photography": "35 mm photography",
        "photorealistic": "Photorealistic",
        "exquisite-detail": "Exquisite detail",
        "food-photography": "Food photography",
        "cinematic-lighting": "Cinematic lighting",
        "portrait-photography": "Portrait photography",
        "award-winning-photography": "Award winning photography",
        "detailed": "Detailed",
        "realistic": "Realistic",
        "hyperrealistic": "Hyperrealistic",
        "4k": "4k",
        "realistic-photography": "Realistic photography",
        "ultra-realistic": "Ultra realistic",
        "volumetric-lighting": "Volumetric lighting",
        "highly-detailed": "Highly detailed",
        "photograph": "Photograph",
        "cinematic": "Cinematic",
        "epic": "Epic",
        "stylized": "Stylized",
        "35-mm-film-photography": "35 mm film photography",
        "cinestill-800t-film-lens": "Cinestill 800t film lens",
        "flare-helios-44-m": "Flare helios 44 m",
        "high-detail": "High detail",
        "telephoto-lense": "Telephoto lense",
        "macro-photograph": "Macro photograph",
        "human-eye": "Human eye",
        "reflection": "Reflection",
        "dslr": "Dslr",
        "award-winning": "Award winning",
        "world-war-2-photo": "World war 2 photo",
        "war-photography": "War photography",
        "film-photography": "Film photography",
        "daylight": "Daylight",
        "ultra-wide-shot": "Ultra wide shot",
        "photorealistic-high-details": "Photorealistic high details",
        "photography-8k-resolution": "Photography 8k resolution",
        "beautiful-detailed": "Beautiful detailed",
        "insanely-intricate-details": "Insanely intricate details",
    },
    "Art styles": {
        "alex-hirsch": "Alex hirsch",
        "alphonse-mucha": "Alphonse mucha",
        "amanda-sage": "Amanda sage",
        "ben-bocquelet": "Ben bocquelet",
        "bernie-wrightson": "Bernie wrightson",
        "canaletto-caspar": "Canaletto caspar",
        "david-friedrich": "David friedrich",
        "claude-monet": "Claude monet",
        "dan-mumford": "Dan mumford",
        "dan-witz": "Dan witz",
        "edward-hopper": "Edward hopper",
        "ferdinand-knab": "Ferdinand knab",
        "gerald-brom": "Gerald brom",
        "greg-rutkowski": "Greg rutkowski",
        "guido-borelli": "Guido borelli",
        "gustav-klimt": "Gustav klimt",
        "gustave-dor\u00e9": "Gustave dor\u00e9",
        "h-r-giger": "h r giger",
        "3j-g-quintel": "3j g quintel",
        "james-gurney": "James gurney",
        "jean-tinguely": "Jean tinguely",
        "jimburns": "Jimburns",
        "josephine-wall": "Josephine wall",
        "julia-pott": "Julia pott",
        "kandinsky": "Kandinsky",
        "kelly-freas": "Kelly freas",
        "leonid-afremov": "Leonid afremov",
        "max-ernst": "Max ernst",
        "moebius": "Moebius",
        "pablo-picasso": "Pablo picasso",
        "pendleton-ward": "Pendleton ward",
        "pino-daeni": "Pino daeni",
        "rafael-santi": "Rafael santi",
        "rebecca-sugar": "Rebecca sugar",
        "rogerdean": "Rogerdean",
        "steven-belledin": "Steven belledin",
        "steven-hillenberg": "Steven hillenberg",
        "studio-ghibli": "Studio ghibli",
        "thomas-kinkade": "Thomas kinkade",
        "tim-burton": "Tim burton",
        "vangogh": "Vangogh",
        "wadim-kashin": "Wadim kashin",
        "wes-anderson": "Wes anderson",
        "zdzistaw-beksi\u00f1ski": "Zdzistaw beksi\u00f1ski",
        "anselm-kiefer": "Anselm kiefer",
        "philippe-garel": "Philippe garel",
        "g\u00e9rard-garouste": "G\u00e9rard garouste",
        "miquel-barcel\u00f3": "Miquel barcel\u00f3",
        "vladimir-veli\u010dkovi\u0107": "Vladimir veli\u010dkovi\u0107",
        "georg-baselitz": "Georg baselitz",
        "pierre-soulages": "Pierre soulages",
        "marlene-dumas": "Marlene dumas",
        "jeff-koons": "Jeff koons",
        "ai-weiwei": "Ai weiwei",
        "yayoi-kusama": "Yayoi kusama",
        "damien-hirst": "Damien hirst",
        "yoko-ono": "Yoko ono",
        "theaster-gates": "Theaster gates",
        "frank-stella": "Frank stella",
        "tania-bruguera": "Tania bruguera",
        "alex-katz": "Alex katz",
        "cindy-sherman": "Cindy sherman",
        "franco-aceves-humana": "Franco aceves humana",
        "mariana-castillo-deball": "Mariana castillo deball",
        "jeannette-betancourt": "Jeannette betancourt",
        "carlos-amorales": "Carlos amorales",
        "silvia-barbescu": "Silvia barbescu",
        "marisa-boullosa": "Marisa boullosa",
        "sof\u00eda-echeverri": "Sof\u00eda echeverri",
        "miguel-calder\u00f3n": "Miguel calder\u00f3n",
        "m\u00e1ximo-gonz\u00e1lez": "M\u00e1ximo gonz\u00e1lez",
        "iv\u00e1n-buenader": "Iv\u00e1n buenader",
        "graciela-iturbide": "Graciela iturbide",
        "emilio-chapela": "Emilio chapela",
        "daniel-guzm\u00e1n": "Daniel guzm\u00e1n",
        "daniel-alcal\u00e1": "Daniel alcal\u00e1",
        "gilda-castillo": "Gilda castillo",
        "rodolfo-d\u00edaz": "Rodolfo d\u00edaz",
        "jan-hendrix": "Jan hendrix",
        "marco-arce": "Marco arce",
        "boris-viskin": "Boris viskin",
        "javier-are\u00e1n": "Javier are\u00e1n",
        "gerda-gruber": "Gerda gruber",
        "cisco-jim\u00e9nez": "Cisco jim\u00e9nez",
        "berta-kolteniuk": "Berta kolteniuk",
        "michel-mallard": "Michel mallard",
        "luciano-matus": "Luciano matus",
        "perla-krauze": "Perla krauze",
        "ricardo-milla": "Ricardo milla",
        "paul-muguet": "Paul muguet",
        "omar-torres": "Omar torres",
        "pia-seiersen": "Pia seiersen",
        "jorge-y\u00e1zpik": "Jorge y\u00e1zpik",
        "ad\u00e1n-paredes": "Ad\u00e1n paredes",
        "dami\u00e1n-ortega": "Dami\u00e1n ortega",
        "pablo-l\u00f3pez-luz": "Pablo l\u00f3pez luz",
        "fernando-ortega": "Fernando ortega",
        "quirarte-ornelas": "Quirarte, ornelas",
        "betsabe\u00e9-romero": "Betsabe\u00e9 romero",
        "gabriel-de-la-mora": "Gabriel de la mora",
        "samuel-mel\u00e9ndrez": "Samuel mel\u00e9ndrez",
        "jos\u00e9-castro-le\u00f1ero": "Jos\u00e9 castro le\u00f1ero",
        "jes\u00fas-lugo-paredes": "Jes\u00fas lugo paredes",
        "roger-von-gunten": "Roger von gunten",
        "miguel-castro-le\u00f1ero": "Miguel castro le\u00f1ero",
        "miguel-\u00e1ngel-cordera": "Miguel \u00e1ngel cordera",
        "miguel-\u00e1ngel-madrigal": "Miguel \u00e1ngel madrigal",
        "yolanda-azul-paulsen": "Yolanda azul paulsen",
        "mario-palacios-kaim": "Mario palacios kaim",
        "patrick-pettersson": "Patrick pettersson",
        "ra\u00fal-ortega-ayala": "Ra\u00fal ortega ayala",
        "renata-petersen": "Renata petersen",
        "alejandro-pintado": "Alejandro pintado",
        "heriberto-quesnel": "Heriberto quesnel",
        "georgina-quintana": "Georgina quintana",
        "pablo-vargas-lugo": "Pablo vargas lugo",
        "roberto-turnbull": "Roberto turnbull",
        "roberto-r\u00e9bora": "Roberto r\u00e9bora",
        "vicente-rojo": "Vicente rojo",
        "nunik-sauret": "Nunik sauret",
        "laura-rosete": "Laura rosete",
        "melanie-smith": "Melanie smith",
        "mario-n\u00fa\u00f1ez": "Mario n\u00fa\u00f1ez",
        "trini": "Trini",
        "hitotzuki": "Hitotzuki",
        "shohei-otomo": "Shohei otomo",
        "lady-aiko": "Lady aiko",
        "dragon-76": "Dragon 76",
        "mina-hamada": "Mina hamada",
        "andy-warhol": "Andy warhol",
        "takashi-murakami": "Takashi murakami",
        "yoshitomo-nara": "Yoshitomo nara",
        "keith-haring": "Keith haring",
        "mark-grotjahn": "Mark grotjahn",
        "peter-doig": "Peter doig",
        "richard-prince": "Richard prince",
        "cecily-brown": "Cecily brown",
        "jean-rene": "Jean rene",
        "hackatao": "Hackatao",
        "beeple": "Beeple",
        "mark-klink-digital-art": "Mark klink digital art",
        "blacke-kathryn": "Blacke kathryn",
        "adam-martinakis": "Adam martinakis",
        "frenetik-void": "Frenetik void",
        "jesu-moratiel": "Jesu moratiel",
        "geray-mena": "Geray mena",
        "magda-arqu\u00e9s": "Magda arqu\u00e9s",
        "octavio-ocampo": "Octavio ocampo",
        "julian-beever": "Julian beever",
    },
    "Art movements": {
        "academic-art": "Academic art",
        "action-painting": "Action painting",
        "art-brut": "Art brut",
        "art-deco": "Art deco",
        "art-nouveau": "Art nouveau",
        "ashcan-school": "Ashcan school",
        "australian-tonalism": "Australian tonalism",
        "baroque": "Baroque",
        "bauhaus": "Bauhaus",
        "brutalism": "Brutalism",
        "childs-drawing": "Child\u2019s drawing",
        "concept-art": "Concept art",
        "concrete-art": "Concrete art",
        "cubism": "Cubism",
        "cubist": "Cubist",
        "detailed-painting": "Detailed painting",
        "expressionism": "Expressionism",
        "fauvism": "Fauvism",
        "film-noir": "Film noir",
        "filmic": "Filmic",
        "fluxus": "Fluxus",
        "folk-art": "Folk art",
        "futurism": "Futurism",
        "geometric-abstract-art": "Geometric abstract art",
        "gothic-art": "Gothic art",
        "graffiti": "Graffiti",
        "harlem-renaissance": "Harlem renaissance",
        "heidelberg-school": "Heidelberg school",
        "hudson-river-school": "Hudson river school",
        "hypermodernism": "Hypermodernism",
        "hyperrealism": "Hyperrealism",
        "impressionism": "Impressionism",
        "kinetic-pointillism": "Kinetic pointillism",
        "lyrical-abstraction": "Lyrical abstraction",
        "mannerism": "Mannerism",
        "matte-painting": "Matte painting",
        "maximalism": "Maximalism",
        "maximalist": "Maximalist",
        "minimalism": "Minimalism",
        "minimalist": "Minimalist",
        "modern-art": "Modern art",
        "modern-european-ink-painting": "Modern european ink painting",
        "movie-poster": "Movie poster",
        "na\u00efve-art": "Na\u00efve art",
        "neo-primitivism": "Neo-primitivism",
        "photorealism": "Photorealism",
        "pointillism": "Pointillism",
        "pop-art": "Pop art",
        "post-impressionism": "Post-impressionism",
        "poster-art": "Poster art",
        "pre-raphaelitism": "Pre-raphaelitism",
        "precisionism": "Precisionism",
        "primitivism": "Primitivism",
        "psychedelic-art": "Psychedelic art",
        "qajar-art": "Qajar art",
        "renaissance-painting": "Renaissance painting",
        "retrofuturism": "Retrofuturism",
        "romanesque": "Romanesque",
        "romanticism": "Romanticism",
        "storybook-illustration": "Storybook illustration",
        "street-art": "Street art",
        "surrealism": "Surrealism",
        "synthetism": "Synthetism",
        "ukiyo-e": "Ukiyo-e",
        "underground-comix": "Underground comix",
        "vorticism": "Vorticism",
    },
    "Descriptive terms": {
        "18th-century-atlas": "18th century atlas",
        "1900s-photograph": "1900s photograph",
        "astral": "Astral",
        "aurora": "Aurora",
        "beautiful": "Beautiful",
        "bismuth": "Bismuth",
        "colorful": "Colorful",
        "complex": "Complex",
        "cosmic": "Cosmic",
        "crepuscule": "Crepuscule",
        "dendritic": "Dendritic",
        "detailed": "Detailed",
        "diffuse": "Diffuse",
        "dystopian": "Dystopian",
        "earth-art": "Earth art",
        "elaborate": "Elaborate",
        "eldritch": "Eldritch",
        "elemental": "Elemental",
        "entangled": "Entangled",
        "ethereal": "Ethereal",
        "expansive": "Expansive",
        "fire": "Fire",
        "firey": "Firey",
        "flickering-light": "Flickering light",
        "futuristic": "Futuristic",
        "galactic": "Galactic",
        "geometric": "Geometric",
        "glowing-neon": "Glowing neon",
        "golden-hour": "Golden hour",
        "gossamer": "Gossamer",
        "heat-wave": "Heat wave",
        "holographic": "Holographic",
        "hyperdetailed": "Hyperdetailed",
        "infinity": "Infinity",
        "intricate": "Intricate",
        "iridescent": "Iridescent",
        "landscape": "Landscape",
        "low-poly": "Low poly",
        "matte-background": "Matte background",
        "meticulous": "Meticulous",
        "moonscape": "Moonscape",
        "mysterious": "Mysterious",
        "noctilucent": "Noctilucent",
        "ominous": "Ominous",
        "ouroboros": "Ouroboros",
        "parallax": "Parallax",
        "photorealistic": "Photorealistic",
        "polished": "Polished",
        "post-apocalyptic": "Post-apocalyptic",
        "psychedelic": "Psychedelic",
        "radiant": "Radiant",
        "retro": "Retro",
        "seascape": "Seascape",
        "serene": "Serene",
        "space": "Space",
        "spiraling": "Spiraling",
        "stygian": "Stygian",
        "sunny": "Sunny",
        "sunshine-rays": "Sunshine rays",
        "synesthesia": "Synesthesia",
        "thunderstorm": "Thunderstorm",
        "tornadic": "Tornadic",
        "twilight": "Twilight",
        "vapor": "Vapor",
    },
    "Design tools and communities": {
        "3d-shading": "3d shading",
        "delight": "Delight",
        "3dexcite-3dsmax": "3dexcite, 3dsmax",
        "appgamekkit": "Appgamekkit",
        "art-of-illusion-artrift-autocad": "Art of illusion, artrift autocad",
        "behance-hd": "Behance hd",
        "cel-shaded": "Cel-shaded",
        "cgsociety": "Cgsociety",
        "cinema4d": "Cinema4d",
        "cryengine": "Cryengine",
        "deviantart": "Deviantart",
        "doodle": "Doodle",
        "addicts-finalrender-flickr-horde3d": "Addicts finalrender, flickr horde3d",
        "imax": "Imax",
        "lightwave": "Lightwave",
        "3d-mandelbulber3d": "3d mandelbulber3d",
        "octane-render": "Octane render",
        "pixiv-polycount-r-art": "Pixiv polycount r, art",
        "rendered-in-blender": "Rendered in blender",
        "shadow-depth": "Shadow depth",
        "sketchfab": "Sketchfab",
        "sketchlab": "Sketchlab",
        "substance": "Substance",
        "designer": "Designer",
        "trending-on-artstation": "Trending on artstation",
        "unity-3d": "Unity 3d",
        "unreal-engine": "Unreal engine",
        "unreal-engine5": "Unreal engine5",
        "volumetric": "Volumetric",
        "lighting": "Lighting",
        "vray": "Vray",
        "zbrush": "Zbrush",
        "zbrush-central": "Zbrush central",
        "nvdia-ray-tracing": "Nvdia ray tracing",
    },
    "Genres": {
        "8bit": "8bit",
        "acrylic-art": "Acrylic art",
        "airbrush-art": "Airbrush art",
        "ambient-occlusion": "Ambient occlusion",
        "brocade": "Brocade",
        "cel-shaded": "Cel-shaded",
        "chalk-art": "Chalk art",
        "charcoal-drawing": "Charcoal drawing",
        "collage": "Collage",
        "digital-art": "Digital art",
        "digital-illustration": "Digital illustration",
        "dye-transfer": "Dye, transfer",
        "faience": "Faience",
        "filigree": "Filigree",
        "fractal": "Fractal",
        "gouache": "Gouache",
        "impasto": "Impasto",
        "ink-drawing": "Ink drawing",
        "kintsugi": "Kintsugi",
        "majolica": "Majolica",
        "mandelbrot": "Mandelbrot",
        "mandelbulb": "Mandelbulb",
        "mixed-media": "Mixed media",
        "mosaic": "Mosaic",
        "needlepoint": "Needlepoint",
        "oil-on-canvas": "Oil on canvas",
        "pastels": "Pastels",
        "pencil-sketch": "Pencil sketch",
        "photoillustration": "Photoillustration",
        "pixel-art": "Pixel art",
        "quilling": "Quilling",
        "resin-cast": "Resin cast",
        "retroism": "Retroism",
        "stipple": "Stipple",
        "tesselation": "Tesselation",
        "thermal-imaging": "Thermal imaging",
        "volumetric-lighting": "Volumetric lighting",
        "watercolor": "Watercolor",
        "wet-brush": "Wet brush",
        "wet-wash": "Wet wash",
        "woodcut": "Woodcut",
    },
    "Fractal": {
        "fractal-forest": "Fractal forest",
        "foggy-cloudy-fractal-art": "Foggy cloudy fractal art",
        "fractals": "Fractals",
        "hyper-detailed": "Hyper detailed",
        "fractal-essence": "Fractal essence",
        "transcending": "Transcending",
        "infinity": "Infinity",
        "time-crystals": "Time crystals",
        "mandelbulb": "Mandelbulb",
        "time-fractals": "Time fractals",
        "neon-fractals": "Neon fractals",
        "sacred-geometry-fractal-art": "Sacred geometry fractal art",
        "fractal-patterns": "Fractal patterns",
        "time": "Time",
        "mandala": "Mandala",
        "golden-ratio": "Golden ratio",
        "psychedelic": "Psychedelic",
        "colorful-relics": "Colorful relics",
        "ethereal": "Ethereal",
        "intricate-fractal-patterned": "Intricate fractal patterned",
        "insanely-detailed": "Insanely detailed",
        "ornate": "Ornate",
        "sinister-resonant-red-glow-white-fractals-creeping-darkness": "Sinister resonant red glow white fractals creeping darkness",
        "grassy-meadow": "Grassy meadow",
        "mother-nature": "Mother nature",
        "buddha-fractal": "Buddha fractal",
        "mandelbrot-set": "Mandelbrot set",
        "ghostly-fractal": "Ghostly fractal",
        "transparent-fractal": "Transparent fractal",
        "generative-art": "Generative art",
        "artstation": "Artstation",
        "deviantart": "Deviantart",
        "dissolving": "Dissolving",
        "abstract-cyberpunk-club-pattern": "Abstract cyberpunk club pattern",
        "glas": "Glas",
    },
    "Matte painting": {
        "caspar-david-friedrich": "Caspar david friedrich",
        "greg-rutkowski": "Greg rutkowski",
        "benoit-b-mandelbrot": "Benoit b mandelbrot",
        "martin-johnson-heade": "Martin johnson heade",
        "noah-bradley": "Noah bradley",
        "interstellar": "Interstellar",
        "fantasy-art": "Fantasy art",
        "wlop": "Wlop",
        "lee-madgwick": "Lee madgwick",
        "andrei-riabovitchev": "Andrei riabovitchev",
        "gustave-dore": "Gustave dore",
        "epic": "Epic",
        "mysterious": "Mysterious",
        "cgsociety": "Cgsociety",
        "peter-mohrbacher": "Peter mohrbacher",
        "desolate-landscape": "Desolate landscape",
        "artstation": "Artstation",
        "vivid-sky": "Vivid sky",
        "tomasz-alen-kopera": "Tomasz alen kopera",
        "thomas-kinkade": "Thomas kinkade",
        "vibrant": "Vibrant",
        "mystical": "Mystical",
        "matte-painting": "Matte painting",
        "cinematic": "Cinematic",
        "cosmic": "Cosmic",
        "concept-art": "Concept art",
        "waves": "Waves",
        "fantasy": "Fantasy",
        "thunder-lightning": "Thunder lightning",
        "detailed-digital-art": "Detailed digital art",
        "cinematic-lighting": "Cinematic lighting",
        "spanish-galleon": "Spanish galleon",
        "storm": "Storm",
        "fantasy-matte-painting": "Fantasy matte painting",
        "twin-suns": "Twin suns",
        "style": "Style",
        "ornate": "Ornate",
        "ominous": "Ominous",
        "single-massive-ancient-alien-pyramid": "Single massive ancient alien pyramid",
        "old-dhaka": "Old dhaka",
        "storm-waves": "Storm waves",
        "vibrant-pastel-tones-colourful-matte-background": "Vibrant pastel tones colourful matte background",
        "trees": "Trees",
        "vladimir-kush": "Vladimir kush",
        "beautiful-detailed-3d-matte-painting": "Beautiful detailed 3d matte painting",
        "night": "Night",
        "makoto-shinkai": "Makoto shinkai",
        "sword": "Sword",
        "tracksuit": "Tracksuit",
        "detailed-matte-color-drawing-trending": "Detailed matte color drawing trending",
        "pixiv-artstation-crunchroll": "Pixiv artstation crunchroll",
        "rivendell-steampunk": "Rivendell steampunk",
        "waterfalls": "Waterfalls",
        "cliff": "Cliff",
        "dappled-golden-lighting": "Dappled golden lighting",
        "photographic": "Photographic",
        "ellen-jewett": "Ellen jewett",
        "ancient-alien-pyramid": "Ancient alien pyramid",
        "beast-tita": "Beast tita",
    },
    "Character": {
        "miyazaki": "Miyazaki",
        "greg-rutkowski": "Greg rutkowski",
        "genndy-tartakovsky": "Genndy tartakovsky",
        "wlop": "Wlop",
        "wayne-reynolds": "Wayne reynolds",
        "don-bluth": "Don bluth",
        "paolo-eleuteri-serpieri": "Paolo eleuteri serpieri",
        "tim-shafer": "Tim shafer",
        "candyland-character": "Candyland character",
        "character-photography": "Character photography",
        "charlie-bowater": "Charlie bowater",
        "character-design": "Character design",
        "nintendo": "Nintendo",
        "pixar": "Pixar",
        "realistic-digital-painting": "Realistic digital painting",
        "fantasy-art": "Fantasy art",
        "digital-painting": "Digital painting",
        "character-designs": "Character designs",
        "goddess": "Goddess",
        "seductive": "Seductive",
        "behance": "Behance",
        "exquisite-detail": "Exquisite detail",
        "fantasy-character": "Fantasy character",
        "cinematic": "Cinematic",
    },
    "Illustration": {
        "illustration": "Illustration",
        "fantasy-art-illustration": "Fantasy art illustration",
        "intricate": "Intricate",
        "ink-illustration": "Ink illustration",
        "line-art": "Line art",
        "vector-art": "Vector art",
        "one-line-illustration": "One line illustration",
        "minimalistic-illustration": "Minimalistic illustration",
        "fine-detailed-lines": "Fine detailed lines",
        "sacred-geometry": "Sacred geometry",
        "detailed-line-work": "Detailed line work",
        "exquisite-detail-perfect-symmetrical": "Exquisite detail perfect symmetrical",
        "silver-details": "Silver details",
        "hyper-detailed": "Hyper detailed",
        "smooth-textures": "Smooth textures",
        "guido-borelli-da-caluso": "Guido borelli da caluso",
        "lithographics": "Lithographics",
        "white-paper": "White paper",
        "vector": "Vector",
        "vector-aesthetics": "Vector aesthetics",
        "smooth": "Smooth",
        "jesper-fjsing": "Jesper fjsing",
        "pen": "Pen",
        "richard-dadd": "Richard dadd",
        "fine-art-illustration": "Fine art illustration",
        "guy-denning": "Guy denning",
    },
    "Cursed": {
        "junji-ito": "Junji ito",
        "beksinski": "Beksinski",
        "grimm": "Grimm",
        "greg-rutkowski": "Greg rutkowski",
        "gustave-dor\u00e9": "Gustave dor\u00e9",
        "zdzis\u0142aw-beksi\u0144ski": "Zdzis\u0142aw beksi\u0144ski",
        "eldritch": "Eldritch",
        "fireflies-glow": "Fireflies glow",
        "apocalypse": "Apocalypse",
        "hr-giger": "Hr giger",
        "andrew-wyeth": "Andrew wyeth",
        "sui-ishida": "Sui ishida",
        "gothic-trees": "Gothic trees",
        "cosmic-horror": "Cosmic horror",
        "creepy": "Creepy",
        "path-leading": "Path leading",
        "black-colored": "Black colored",
        "magic-fireflies": "Magic fireflies",
        "dark-atmospheric-lighting": "Dark atmospheric lighting",
        "volumetrics": "Volumetrics",
        "mystical-creepy": "Mystical creepy",
        "skulls": "Skulls",
        "space": "Space",
        "black-metal": "Black metal",
        "creepy-creature": "Creepy creature",
        "cinematic-landscape": "Cinematic landscape",
        "true-monster-visage": "True monster visage",
        "horror-spooky": "Horror spooky",
        "dark-glowing": "Dark glowing",
    },
    "3d": {
        "artstation": "Artstation",
        "renderman": "Renderman",
        "octane-render": "Octane render",
        "3d-render": "3d render",
        "high-quality-3d-render": "High quality 3d render",
        "pixar-movie": "Pixar movie",
        "cry-engine": "Cry engine",
        "lumion-render": "Lumion render",
        "zbrush": "Zbrush",
        "autodesk-3d-rendering": "Autodesk 3d rendering",
        "v-ray-collection": "V ray collection",
        "maverick-studio": "Maverick studio",
        "arnold-3d-render": "Arnold 3d render",
        "blender-render": "Blender render",
        "indigo-renderer": "Indigo renderer",
        "redshift-render": "Redshift render",
        "enscape-render": "Enscape render",
        "maxwell-render": "Maxwell render",
        "luxcorerender": "Luxcorerender",
        "marmoset-render": "Marmoset render",
        "3d-sculpture": "3d sculpture",
        "unreal-engine": "Unreal engine",
        "blender": "Blender",
        "cinema4d": "Cinema4d",
        "nvidia": "Nvidia",
        "ultrarealistic": "Ultrarealistic",
        "cgsociety": "Cgsociety",
        "volumetric-light": "Volumetric light",
        "lightrays": "Lightrays",
        "atmospheric": "Atmospheric",
        "dreamworks": "Dreamworks",
        "3d-character-model": "3d character model",
    },
    "Painting": {
        "john-harris": "John harris",
        "animation-background-painting": "Animation background painting",
        "caspar-david-friedrich": "Caspar david friedrich",
        "beksinski": "Beksinski",
        "macabre": "Macabre",
        "burtonesque": "Burtonesque",
        "oil-painting": "Oil painting",
        "craig-mullins": "Craig mullins",
        "life-portrait": "Life portrait",
        "john-everett-millais": "John everett millais",
        "beautiful-painting": "Beautiful painting",
        "rembrandt": "Rembrandt",
        "salvador-dali": "Salvador dali",
        "sci-fi-landscape-painting": "Sci fi landscape painting",
        "dramatic-lighting": "Dramatic lighting",
        "van-gogh": "Van gogh",
        "leonardo-da-vinci": "Leonardo da vinci",
        "whimsical-painting": "Whimsical painting",
        "hr-giger": "Hr giger",
        "singer-sargent": "Singer sargent",
        "dan-mumford": "Dan mumford",
        "jim-burns": "Jim burns",
        "thomas-kincade": "Thomas kincade",
        "greg-rutkowski": "Greg rutkowski",
        "surrealist-oil-painting": "Surrealist oil painting",
        "matte-painting": "Matte painting",
        "delicate": "Delicate",
        "digital-painting": "Digital painting",
        "striking-hyper-real-painting": "Striking hyper real painting",
        "abstract-painting": "Abstract painting",
        "halo": "Halo",
        "comic-book-style-portrait-painting": "Comic book style portrait painting",
        "saintly-halo": "Saintly halo",
        "edward-hopper": "Edward hopper",
        "classical-painting": "Classical painting",
        "daniel-gerhartz": "Daniel gerhartz",
        "noah-bradley": "Noah bradley",
        "lucius": "Lucius",
    },
}
